#!/usr/bin/env bash
set -euo pipefail
trap 'rc=$?; echo "" >&2; echo "install.sh: FAILED at line $LINENO (exit $rc)" >&2' ERR

INSTALL_DIR="/opt/nasr"
SERVICE_USER="${NASR_USER:-$(whoami)}"

echo "=== Nasr Installer ==="

# 1. Node.js 22
if ! command -v node &>/dev/null || [[ "$(node -v | cut -d. -f1 | tr -d v)" -lt 22 ]]; then
  echo "Installing Node.js 22 LTS..."
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
echo "Node.js $(node -v)"

# 2. pnpm
if ! command -v pnpm &>/dev/null; then
  echo "Installing pnpm..."
  sudo npm install -g pnpm
fi
echo "pnpm $(pnpm -v)"

# 3. Copy project files
echo "Setting up $INSTALL_DIR..."
sudo mkdir -p "$INSTALL_DIR"
sudo chown "$SERVICE_USER":"$SERVICE_USER" "$INSTALL_DIR"
# data/ and backups/ are anchored with a leading slash: they name the runtime
# directories at the install root only. Unanchored, rsync also matches
# apps/web/src/data, which silently drops the client data layer from the build.
rsync -a --exclude node_modules --exclude .output --exclude .git \
  --exclude /data --exclude /backups --exclude /.env ./ "$INSTALL_DIR/"

cd "$INSTALL_DIR"

# 3b. Environment file. Created once, never overwritten — this is the single
# source of truth for runtime config: nasr.service reads it via
# EnvironmentFile=, and the rest of this script sources it below.
if [ ! -f "$INSTALL_DIR/.env" ]; then
  echo "Creating $INSTALL_DIR/.env..."
  cat > "$INSTALL_DIR/.env" <<ENVFILE
# Generated by install.sh. Edit freely; re-running the installer keeps it.
# systemd parses this file, so: no quotes, no export, no inline comments.
NODE_ENV=production
PORT=8080
HOST=0.0.0.0
NASR_DB_PATH=$INSTALL_DIR/data/nasr.db
ENVFILE
  chmod 600 "$INSTALL_DIR/.env"
else
  echo "Keeping existing $INSTALL_DIR/.env"
fi

# Source it so migrations, the PIN bootstrap and the build all agree with the
# values the service will run with.
set -a
# shellcheck disable=SC1091
. "$INSTALL_DIR/.env"
set +a
export NASR_DB_PATH="${NASR_DB_PATH:-$INSTALL_DIR/data/nasr.db}"

# 4. Install dependencies
echo "Installing dependencies..."
# confirmModulesPurge=false: a re-run over an existing node_modules built by a
# different pnpm version otherwise aborts when there is no TTY.
pnpm install --frozen-lockfile --config.confirmModulesPurge=false

# better-sqlite3 ships prebuilt binaries for every platform inside its tarball
# and lib/binding.js prefers prebuilds/<platform>-<arch>.node over anything
# node-gyp produces. The linux-arm64 prebuild is linked against glibc 2.38,
# newer than Raspberry Pi OS bookworm's 2.36, so it fails to dlopen. The package
# also has no install/postinstall script, which is why `pnpm rebuild` is a no-op
# here. Test whether the binding actually loads; if not, force a source build and
# put the result where binding.js will look first.
# The probe must construct a Database: require() alone never dlopens the binary,
# binding.js is only reached from the Database constructor.
echo "Checking better-sqlite3 native binding..."
if (cd "$INSTALL_DIR/apps/web" && node -e "new (require('better-sqlite3'))(':memory:').close()") 2>/dev/null; then
  echo "Prebuilt binary works."
else
  echo "Prebuilt binary is unusable on this system. Building from source (this takes several minutes)..."
  command -v gcc &>/dev/null && command -v make &>/dev/null || sudo apt-get install -y build-essential
  command -v python3 &>/dev/null || sudo apt-get install -y python3
  BS3_DIR=$(cd "$INSTALL_DIR/apps/web" && node -e "const p=require('path'); console.log(p.dirname(p.dirname(require.resolve('better-sqlite3'))))")
  (
    cd "$BS3_DIR"
    # --force_build=1: binding.gyp otherwise detects the bundled prebuild and skips compiling
    npx --yes node-gyp rebuild --release --force_build=1
    PREBUILD="prebuilds/$(node -p "process.platform + '-' + process.arch").node"
    # rm before cp: pnpm hardlinks package files into the global store, so
    # writing in place would corrupt the store copy for every other project.
    rm -f "$PREBUILD"
    cp build/Release/better_sqlite3.node "$PREBUILD"
  )
  (cd "$INSTALL_DIR/apps/web" && node -e "new (require('better-sqlite3'))(':memory:').close(); console.log('Source-built better-sqlite3 loads OK.')")
fi

# 5. Run migrations
echo "Running database migrations..."
mkdir -p "$(dirname "$NASR_DB_PATH")"
pnpm db:migrate

# 6. Set PIN
if [ -z "${NASR_PIN:-}" ]; then
  echo ""
  read -rsp "Set your PIN (min 4 chars): " pin
  echo ""
  if [ ${#pin} -lt 4 ]; then
    echo "PIN must be at least 4 characters."
    exit 1
  fi
else
  pin="$NASR_PIN"
  echo "Using PIN from NASR_PIN environment variable."
fi

# Set PIN directly in the DB. Run from apps/web: better-sqlite3 is a dependency
# of that workspace package, so it does not resolve from the repo root.
# The PIN is passed via env, never interpolated into the JS source.
(
cd "$INSTALL_DIR/apps/web"
NASR_PIN_VALUE="$pin" node --input-type=commonjs -e "
  const Database = require('better-sqlite3');
  const crypto = require('crypto');
  const db = new Database(process.env.NASR_DB_PATH);
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(process.env.NASR_PIN_VALUE, salt, 64).toString('hex');
  db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('pin_hash', salt + ':' + hash);
  db.close();
  console.log('PIN set successfully.');
"
)

# 7. Build
echo "Building..."
pnpm build

# 8. Install systemd units
echo "Installing systemd services..."
sudo cp "$INSTALL_DIR/nasr.service" /etc/systemd/system/
sudo cp "$INSTALL_DIR/nasr-backup.service" /etc/systemd/system/
sudo cp "$INSTALL_DIR/nasr-backup.timer" /etc/systemd/system/

# Update user in both units. The backup unit must run as the same user, or it
# creates root-owned backups the app user cannot write to or restore from.
sudo sed -i "s/User=rehan/User=$SERVICE_USER/" /etc/systemd/system/nasr.service
sudo sed -i "s/User=rehan/User=$SERVICE_USER/" /etc/systemd/system/nasr-backup.service

# An earlier install may have left a root-owned backups directory behind.
sudo mkdir -p "$INSTALL_DIR/backups"
sudo chown -R "$SERVICE_USER":"$SERVICE_USER" "$INSTALL_DIR/backups"

sudo systemctl daemon-reload
sudo systemctl enable --now nasr.service
sudo systemctl enable --now nasr-backup.timer

echo ""
echo "=== Nasr is running! ==="
echo "Open http://$(hostname -I | awk '{print $1}'):8080 in your browser."
echo ""
