/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline.index'
import { Route as PipelineNewRouteImport } from './routes/pipeline.new'
import { Route as PipelineIdRouteImport } from './routes/pipeline.$id'
import { Route as DeenObservationsRouteImport } from './routes/deen.observations'
import { Route as DeenHistoryRouteImport } from './routes/deen.history'
import { Route as ApiV1SettingsRouteImport } from './routes/api.v1.settings'
import { Route as ApiV1ExportRouteImport } from './routes/api.v1.export'
import { Route as ApiV1SettingsResetRouteImport } from './routes/api.v1.settings.reset'
import { Route as ApiV1PipelineTouchesRouteImport } from './routes/api.v1.pipeline.touches'
import { Route as ApiV1PipelineOpportunitiesRouteImport } from './routes/api.v1.pipeline.opportunities'
import { Route as ApiV1DeenSadaqahRouteImport } from './routes/api.v1.deen.sadaqah'
import { Route as ApiV1DeenObservationsRouteImport } from './routes/api.v1.deen.observations'
import { Route as ApiV1DeenDaysRouteImport } from './routes/api.v1.deen.days'
import { Route as ApiV1AuthStatusRouteImport } from './routes/api.v1.auth.status'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api.v1.auth.logout'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api.v1.auth.login'
import { Route as ApiV1PipelineOpportunityIdRouteImport } from './routes/api.v1.pipeline.opportunity.$id'
import { Route as ApiV1DeenDayDateRouteImport } from './routes/api.v1.deen.day.$date'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelineRoute,
} as any)
const PipelineNewRoute = PipelineNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PipelineRoute,
} as any)
const PipelineIdRoute = PipelineIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PipelineRoute,
} as any)
const DeenObservationsRoute = DeenObservationsRouteImport.update({
  id: '/deen/observations',
  path: '/deen/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const DeenHistoryRoute = DeenHistoryRouteImport.update({
  id: '/deen/history',
  path: '/deen/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsRoute = ApiV1SettingsRouteImport.update({
  id: '/api/v1/settings',
  path: '/api/v1/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportRoute = ApiV1ExportRouteImport.update({
  id: '/api/v1/export',
  path: '/api/v1/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsResetRoute = ApiV1SettingsResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ApiV1SettingsRoute,
} as any)
const ApiV1PipelineTouchesRoute = ApiV1PipelineTouchesRouteImport.update({
  id: '/api/v1/pipeline/touches',
  path: '/api/v1/pipeline/touches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PipelineOpportunitiesRoute =
  ApiV1PipelineOpportunitiesRouteImport.update({
    id: '/api/v1/pipeline/opportunities',
    path: '/api/v1/pipeline/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DeenSadaqahRoute = ApiV1DeenSadaqahRouteImport.update({
  id: '/api/v1/deen/sadaqah',
  path: '/api/v1/deen/sadaqah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeenObservationsRoute = ApiV1DeenObservationsRouteImport.update({
  id: '/api/v1/deen/observations',
  path: '/api/v1/deen/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeenDaysRoute = ApiV1DeenDaysRouteImport.update({
  id: '/api/v1/deen/days',
  path: '/api/v1/deen/days',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthStatusRoute = ApiV1AuthStatusRouteImport.update({
  id: '/api/v1/auth/status',
  path: '/api/v1/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PipelineOpportunityIdRoute =
  ApiV1PipelineOpportunityIdRouteImport.update({
    id: '/api/v1/pipeline/opportunity/$id',
    path: '/api/v1/pipeline/opportunity/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DeenDayDateRoute = ApiV1DeenDayDateRouteImport.update({
  id: '/api/v1/deen/day/$date',
  path: '/api/v1/deen/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/deen/history': typeof DeenHistoryRoute
  '/deen/observations': typeof DeenObservationsRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/pipeline/new': typeof PipelineNewRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/settings': typeof ApiV1SettingsRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/status': typeof ApiV1AuthStatusRoute
  '/api/v1/deen/days': typeof ApiV1DeenDaysRoute
  '/api/v1/deen/observations': typeof ApiV1DeenObservationsRoute
  '/api/v1/deen/sadaqah': typeof ApiV1DeenSadaqahRoute
  '/api/v1/pipeline/opportunities': typeof ApiV1PipelineOpportunitiesRoute
  '/api/v1/pipeline/touches': typeof ApiV1PipelineTouchesRoute
  '/api/v1/settings/reset': typeof ApiV1SettingsResetRoute
  '/api/v1/deen/day/$date': typeof ApiV1DeenDayDateRoute
  '/api/v1/pipeline/opportunity/$id': typeof ApiV1PipelineOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/deen/history': typeof DeenHistoryRoute
  '/deen/observations': typeof DeenObservationsRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/pipeline/new': typeof PipelineNewRoute
  '/pipeline': typeof PipelineIndexRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/settings': typeof ApiV1SettingsRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/status': typeof ApiV1AuthStatusRoute
  '/api/v1/deen/days': typeof ApiV1DeenDaysRoute
  '/api/v1/deen/observations': typeof ApiV1DeenObservationsRoute
  '/api/v1/deen/sadaqah': typeof ApiV1DeenSadaqahRoute
  '/api/v1/pipeline/opportunities': typeof ApiV1PipelineOpportunitiesRoute
  '/api/v1/pipeline/touches': typeof ApiV1PipelineTouchesRoute
  '/api/v1/settings/reset': typeof ApiV1SettingsResetRoute
  '/api/v1/deen/day/$date': typeof ApiV1DeenDayDateRoute
  '/api/v1/pipeline/opportunity/$id': typeof ApiV1PipelineOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/deen/history': typeof DeenHistoryRoute
  '/deen/observations': typeof DeenObservationsRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/pipeline/new': typeof PipelineNewRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/settings': typeof ApiV1SettingsRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/status': typeof ApiV1AuthStatusRoute
  '/api/v1/deen/days': typeof ApiV1DeenDaysRoute
  '/api/v1/deen/observations': typeof ApiV1DeenObservationsRoute
  '/api/v1/deen/sadaqah': typeof ApiV1DeenSadaqahRoute
  '/api/v1/pipeline/opportunities': typeof ApiV1PipelineOpportunitiesRoute
  '/api/v1/pipeline/touches': typeof ApiV1PipelineTouchesRoute
  '/api/v1/settings/reset': typeof ApiV1SettingsResetRoute
  '/api/v1/deen/day/$date': typeof ApiV1DeenDayDateRoute
  '/api/v1/pipeline/opportunity/$id': typeof ApiV1PipelineOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/login'
    | '/pipeline'
    | '/review'
    | '/settings'
    | '/deen/history'
    | '/deen/observations'
    | '/pipeline/$id'
    | '/pipeline/new'
    | '/pipeline/'
    | '/api/v1/export'
    | '/api/v1/settings'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/status'
    | '/api/v1/deen/days'
    | '/api/v1/deen/observations'
    | '/api/v1/deen/sadaqah'
    | '/api/v1/pipeline/opportunities'
    | '/api/v1/pipeline/touches'
    | '/api/v1/settings/reset'
    | '/api/v1/deen/day/$date'
    | '/api/v1/pipeline/opportunity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/login'
    | '/review'
    | '/settings'
    | '/deen/history'
    | '/deen/observations'
    | '/pipeline/$id'
    | '/pipeline/new'
    | '/pipeline'
    | '/api/v1/export'
    | '/api/v1/settings'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/status'
    | '/api/v1/deen/days'
    | '/api/v1/deen/observations'
    | '/api/v1/deen/sadaqah'
    | '/api/v1/pipeline/opportunities'
    | '/api/v1/pipeline/touches'
    | '/api/v1/settings/reset'
    | '/api/v1/deen/day/$date'
    | '/api/v1/pipeline/opportunity/$id'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/login'
    | '/pipeline'
    | '/review'
    | '/settings'
    | '/deen/history'
    | '/deen/observations'
    | '/pipeline/$id'
    | '/pipeline/new'
    | '/pipeline/'
    | '/api/v1/export'
    | '/api/v1/settings'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/status'
    | '/api/v1/deen/days'
    | '/api/v1/deen/observations'
    | '/api/v1/deen/sadaqah'
    | '/api/v1/pipeline/opportunities'
    | '/api/v1/pipeline/touches'
    | '/api/v1/settings/reset'
    | '/api/v1/deen/day/$date'
    | '/api/v1/pipeline/opportunity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  DeenHistoryRoute: typeof DeenHistoryRoute
  DeenObservationsRoute: typeof DeenObservationsRoute
  ApiV1ExportRoute: typeof ApiV1ExportRoute
  ApiV1SettingsRoute: typeof ApiV1SettingsRouteWithChildren
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthStatusRoute: typeof ApiV1AuthStatusRoute
  ApiV1DeenDaysRoute: typeof ApiV1DeenDaysRoute
  ApiV1DeenObservationsRoute: typeof ApiV1DeenObservationsRoute
  ApiV1DeenSadaqahRoute: typeof ApiV1DeenSadaqahRoute
  ApiV1PipelineOpportunitiesRoute: typeof ApiV1PipelineOpportunitiesRoute
  ApiV1PipelineTouchesRoute: typeof ApiV1PipelineTouchesRoute
  ApiV1DeenDayDateRoute: typeof ApiV1DeenDayDateRoute
  ApiV1PipelineOpportunityIdRoute: typeof ApiV1PipelineOpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/pipeline/new': {
      id: '/pipeline/new'
      path: '/new'
      fullPath: '/pipeline/new'
      preLoaderRoute: typeof PipelineNewRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/pipeline/$id': {
      id: '/pipeline/$id'
      path: '/$id'
      fullPath: '/pipeline/$id'
      preLoaderRoute: typeof PipelineIdRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/deen/observations': {
      id: '/deen/observations'
      path: '/deen/observations'
      fullPath: '/deen/observations'
      preLoaderRoute: typeof DeenObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deen/history': {
      id: '/deen/history'
      path: '/deen/history'
      fullPath: '/deen/history'
      preLoaderRoute: typeof DeenHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings': {
      id: '/api/v1/settings'
      path: '/api/v1/settings'
      fullPath: '/api/v1/settings'
      preLoaderRoute: typeof ApiV1SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export': {
      id: '/api/v1/export'
      path: '/api/v1/export'
      fullPath: '/api/v1/export'
      preLoaderRoute: typeof ApiV1ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/reset': {
      id: '/api/v1/settings/reset'
      path: '/reset'
      fullPath: '/api/v1/settings/reset'
      preLoaderRoute: typeof ApiV1SettingsResetRouteImport
      parentRoute: typeof ApiV1SettingsRoute
    }
    '/api/v1/pipeline/touches': {
      id: '/api/v1/pipeline/touches'
      path: '/api/v1/pipeline/touches'
      fullPath: '/api/v1/pipeline/touches'
      preLoaderRoute: typeof ApiV1PipelineTouchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pipeline/opportunities': {
      id: '/api/v1/pipeline/opportunities'
      path: '/api/v1/pipeline/opportunities'
      fullPath: '/api/v1/pipeline/opportunities'
      preLoaderRoute: typeof ApiV1PipelineOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deen/sadaqah': {
      id: '/api/v1/deen/sadaqah'
      path: '/api/v1/deen/sadaqah'
      fullPath: '/api/v1/deen/sadaqah'
      preLoaderRoute: typeof ApiV1DeenSadaqahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deen/observations': {
      id: '/api/v1/deen/observations'
      path: '/api/v1/deen/observations'
      fullPath: '/api/v1/deen/observations'
      preLoaderRoute: typeof ApiV1DeenObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deen/days': {
      id: '/api/v1/deen/days'
      path: '/api/v1/deen/days'
      fullPath: '/api/v1/deen/days'
      preLoaderRoute: typeof ApiV1DeenDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/status': {
      id: '/api/v1/auth/status'
      path: '/api/v1/auth/status'
      fullPath: '/api/v1/auth/status'
      preLoaderRoute: typeof ApiV1AuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pipeline/opportunity/$id': {
      id: '/api/v1/pipeline/opportunity/$id'
      path: '/api/v1/pipeline/opportunity/$id'
      fullPath: '/api/v1/pipeline/opportunity/$id'
      preLoaderRoute: typeof ApiV1PipelineOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deen/day/$date': {
      id: '/api/v1/deen/day/$date'
      path: '/api/v1/deen/day/$date'
      fullPath: '/api/v1/deen/day/$date'
      preLoaderRoute: typeof ApiV1DeenDayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PipelineRouteChildren {
  PipelineIdRoute: typeof PipelineIdRoute
  PipelineNewRoute: typeof PipelineNewRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelineIdRoute: PipelineIdRoute,
  PipelineNewRoute: PipelineNewRoute,
  PipelineIndexRoute: PipelineIndexRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

interface ApiV1SettingsRouteChildren {
  ApiV1SettingsResetRoute: typeof ApiV1SettingsResetRoute
}

const ApiV1SettingsRouteChildren: ApiV1SettingsRouteChildren = {
  ApiV1SettingsResetRoute: ApiV1SettingsResetRoute,
}

const ApiV1SettingsRouteWithChildren = ApiV1SettingsRoute._addFileChildren(
  ApiV1SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRouteWithChildren,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  DeenHistoryRoute: DeenHistoryRoute,
  DeenObservationsRoute: DeenObservationsRoute,
  ApiV1ExportRoute: ApiV1ExportRoute,
  ApiV1SettingsRoute: ApiV1SettingsRouteWithChildren,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthStatusRoute: ApiV1AuthStatusRoute,
  ApiV1DeenDaysRoute: ApiV1DeenDaysRoute,
  ApiV1DeenObservationsRoute: ApiV1DeenObservationsRoute,
  ApiV1DeenSadaqahRoute: ApiV1DeenSadaqahRoute,
  ApiV1PipelineOpportunitiesRoute: ApiV1PipelineOpportunitiesRoute,
  ApiV1PipelineTouchesRoute: ApiV1PipelineTouchesRoute,
  ApiV1DeenDayDateRoute: ApiV1DeenDayDateRoute,
  ApiV1PipelineOpportunityIdRoute: ApiV1PipelineOpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
